artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ashay-thamankar/raw-data-to-practice/raw/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/staus.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib
  test_array_path: artifacts/data_transformation/test_array.joblib
  train_array_path: artifacts/data_transformation/train_array.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  test_array_path: artifacts/data_transformation/test_array.joblib
  train_array_path: artifacts/data_transformation/train_array.joblib
  best_params: artifacts/data_transformation/best_params.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_array_path: artifacts/data_transformation/test_array.joblib
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

model_prediction:
  model_path: artifacts/model_trainer/model.joblib
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib
  params_path: artifacts/data_transformation/best_params.joblib
  train_array_path: artifacts/data_transformation/train_array.joblib



  